os: linux
language: node_js
node_js:
- lts/*
script: npm run coverage
deploy:
  edge: true
  provider: npm
  email: gert.sonderby@gmail.com
  api_token:
    secure: O0c/LREaxOshp4LbI5flCIyWFtdVhJEkUE1Z1B/bf7SycxfaC7F9tROlLYNvagXjxIOgShveVMwweoj8WiPSLEQ/IrInYmumwF/OWNAEGrjAUfHQCjeuq68c4KhLWpBFKCWPHIroBiYrJHrBo2SObQol9OnViwwiwC1qLNO7q1NAOW0UpN7NlSkwf478sNA8kbVXlkxQwCoDiC9+TmE8XWu/pVpod1YIZtnUqaA5qm7WyRiECWBxZVnu/mWnJ0AVc9FdueSpadd7GguueZt0nP32he2oGqsCvantoz86eVUE7VB+MLwOPnaV1vur768kZTyNYXZIFcYpSB21RQOnaGGLeRwiYGj0v15CTHhVgbC8YXUu9PfYQBifZZJtL0j2MXa/5Z0sWbkZ4/rpyH7vaFlg0aOgXeyMe7iCF9bpPjtLWbNd8WWrm8JTMjLpkjtTK5+pX6Sb4Xjw1HWFjFBYL6kXPyINPf/DlPHM6wNjxH612ild/mA8cCqzd7CcpDbjCSLKfywc9o55QHVftajCr5QQGGKMdMRUnSgGZYu9vj1maQi6LZigQ+NBjSiJEKixsKv/SyZajmaaYndVUwAkHd3vfqfcKHdKQKkAPhBZDIDSkJP1dBPxk4UgJlXaA2v+ic9qmPUuN87vFxmiS9osk+GIlgByW81/ARs4DIH1Wck=
  on:
    tags: true
    condition: $TRAVIS_NODE_VERSION = 12
    repo: gertsonderby/unexpected-generator
